<h1>Contexto:<h1>
Habilidades: 
- Telekinesis
- Telepatia

Se va a medir el tiempo en generaciones

In [42]:
import numpy as np
matriz_transicion= np.array([[0.07,0.04,0.89],
                            [0.1,0.07, 0.83],
                            [0.15,0.17,0.68]])
vector_v= np.array([0.28,0.26,0.46]) 
# sacar las probabilidaddes
#Siguiente generacion T = 4 5° generacion
ejemplo = vector_v.dot(matriz_transicion)
ejemplo

array([0.1146, 0.1076, 0.7778])

In [43]:
#6° generacion
ejemplo2 = np.linalg.matrix_power(matriz_transicion, 2)
print(ejemplo2)

[[0.1424 0.1569 0.7007]
 [0.1385 0.15   0.7115]
 [0.1295 0.1335 0.737 ]]


In [44]:
ejemplo_vector = ejemplo.dot(ejemplo2)
ejemplo_vector

array([0.13194674, 0.13795704, 0.73009622])

In [45]:
#7° Generacion
ejemplo2 = np.linalg.matrix_power(matriz_transicion, 3)
print(ejemplo2)

[[0.130763 0.135798 0.733439]
 [0.13142  0.136995 0.731585]
 [0.132965 0.139815 0.72722 ]]


In [46]:
ejemplo_vector2 = ejemplo_vector.dot(ejemplo2)
ejemplo_vector2

array([0.13246131, 0.13889593, 0.72864276])